# Generated by Django 4.0 on 2022-12-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apex_deployment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
