# Generated by Django 4.0 on 2022-12-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apex_deployment_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apex',
            options={'verbose_name': 'APEX', 'verbose_name_plural': 'APEXs'},
        ),
        migrations.AlterModelOptions(
            name='apex_deployment',
            options={'verbose_name': 'APEX Deployment', 'verbose_name_plural': 'APEX Deployments'},
        ),
        migrations.AlterModelOptions(
            name='apex_version',
            options={'verbose_name': 'APEX Version', 'verbose_name_plural': 'APEX Versions'},
        ),
        migrations.CreateModel(
            name='APEX_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.CharField(max_length=100)),
                ('time_stamp', models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=21, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apex_deployment', to='api.apex_deployment')),
            ],
        ),
    ]
