# Generated by Django 4.0 on 2022-12-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apex_options_alter_apex_deployment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apex_data',
            options={'verbose_name': 'APEX Data', 'verbose_name_plural': 'APEX Data'},
        ),
    ]
