# Generated by Django 4.0 on 2022-12-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_customer'),
        ('api', '0004_alter_apex_data_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPLOYMENT_SITE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apex_deployment', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Deploymnt Site',
                'verbose_name_plural': 'Deploymnt Sites',
            },
        ),
    ]
