# Generated by Django 4.0 on 2022-12-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deployment_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment_site',
            options={'verbose_name': 'Deployment Site', 'verbose_name_plural': 'Deployment Sites'},
        ),
    ]
