# Generated by Django 4.0 on 2022-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_deployment_site_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment_site',
            name='post_to_database',
            field=models.BooleanField(default=True),
        ),
    ]
