# Generated by Django 4.0 on 2022-12-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deployment_site_post_to_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment_site',
            old_name='post_to_database',
            new_name='post_data_to_database',
        ),
    ]
