# Generated by Django 4.0 on 2022-12-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_post_to_database_deployment_site_post_data_to_database'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APEX_DATA',
            new_name='APEX_RAW_DATA',
        ),
    ]
