# Generated by Django 4.0 on 2022-12-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_apex_data_apex_raw_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='APEX_RAW_DATA_FILENAMES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('written_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apex_raw_data',
            options={'verbose_name': 'APEX Raw Data', 'verbose_name_plural': 'APEX Raw Data'},
        ),
    ]
