# Generated by Django 4.0 on 2022-12-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_apex_raw_data_filenames_alter_apex_raw_data_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apex_raw_data_filenames',
            old_name='written_on',
            new_name='added_on',
        ),
    ]
