# Generated by Django 4.0 on 2022-12-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_written_on_apex_raw_data_filenames_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apex_raw_data_filenames',
            options={'verbose_name': 'APEX Data Filename', 'verbose_name_plural': 'APEX Data Filenames'},
        ),
        migrations.AddField(
            model_name='apex_raw_data_filenames',
            name='entries_written',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
