# Generated by Django 4.0 on 2022-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_apex_raw_data_filenames_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment_site',
            name='post_data_to_database',
        ),
        migrations.AddField(
            model_name='apex_deployment',
            name='post_data_to_database',
            field=models.BooleanField(default=True),
        ),
    ]
