# Generated by Django 4.0 on 2022-12-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_deployment_site_post_data_to_database_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apex_deployment',
            name='deployment_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_site', to='api.deployment_site'),
        ),
    ]
