# Generated by Django 4.0 on 2022-12-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_apex_deployment_deployment_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apex_deployment',
            name='location',
        ),
    ]
