# Generated by Django 4.0 on 2022-12-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_apex_deployment_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment_site',
            old_name='owner',
            new_name='contact',
        ),
    ]
