# Generated by Django 4.0 on 2022-12-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_owner_deployment_site_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment_site',
            name='directory_name',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
