# Generated by Django 4.0 on 2022-12-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_apex_raw_data_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apex_raw_data',
            name='uniqueID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
