# Generated by Django 4.0 on 2022-12-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_apex_raw_data_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apex_raw_data',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='apex_raw_data',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
