# Generated by Django 4.0 on 2022-12-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_apex_raw_data_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apex_raw_data',
            old_name='time_stamp',
            new_name='gps_hhmmss',
        ),
    ]
