# Generated by Django 4.0 on 2022-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_time_stamp_apex_raw_data_gps_hhmmss'),
    ]

    operations = [
        migrations.AddField(
            model_name='apex_deployment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
