# Generated by Django 4.0 on 2022-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_apex_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apex_deployment',
            name='utm_zone',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
