# Generated by Django 4.0 on 2022-12-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_apex_deployment_utm_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='apex_deployment',
            name='gps_format',
            field=models.CharField(choices=[('RTK', 'RTK'), ('SLAM', 'SLAM')], default='SLAM', max_length=20),
        ),
    ]
