# Generated by Django 4.0 on 2022-12-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_apex_deployment_gps_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apex_deployment',
            name='gps_format',
        ),
    ]
