# Generated by Django 4.0 on 2022-12-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_apex_deployment_gps_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apex_raw_data',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='apex_raw_data',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
    ]
