# Generated by Django 4.0 on 2022-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_apex_raw_data_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apex_deployment',
            name='queue_for_decode',
            field=models.BooleanField(default=False),
        ),
    ]
