# Generated by Django 4.0 on 2022-12-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_apex_deployment_queue_for_decode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apex_deployment',
            name='post_data_to_database',
        ),
    ]
