# Generated by Django 4.0 on 2022-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_apex_deployment_post_data_to_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apex_deployment',
            name='utm_zone',
            field=models.CharField(default='', max_length=3),
        ),
    ]
