# Generated by Django 4.1.4 on 2023-01-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_user_customer_contact'),
        ('api', '0032_alter_apex_deployment_utm_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment_site',
            name='contact',
        ),
        migrations.AddField(
            model_name='apex_deployment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apex_deployment', to='customers.customer'),
        ),
    ]
