# Generated by Django 4.0 on 2022-12-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CUSTOMERS',
            new_name='CUSTOMER',
        ),
    ]
